# -*- coding: utf-8 -*-
"""image_enhancement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TzpjK1ywgWqncM5aj1GcxI62dAkA507R
"""

!git clone https://github.com/pksvision/Deep-WaveNet-Underwater-Image-Restoration.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/Deep-WaveNet-Underwater-Image-Restoration/uie_uieb

!python test.py



from google.colab.patches import cv2_imshow

from skimage import io
import cv2 as cv


image1 = io.imread('./hazy_test/mud1.png')
image_1 = cv.cvtColor(image1, cv.COLOR_BGR2RGB)
cv2_imshow(image_1)


image2 = io.imread('./hazy_test/mud2.png')
image_2 = cv.cvtColor(image2, cv.COLOR_BGR2RGB)
cv2_imshow(image_2)

image1 = io.imread('./facades/Ours_UIEB/mud1.png')
image_1 = cv.cvtColor(image1, cv.COLOR_BGR2RGB)
cv2_imshow(image_1)
image2 = io.imread('./facades/Ours_UIEB/mud2.png')
image_2 = cv.cvtColor(image2, cv.COLOR_BGR2RGB)
cv2_imshow(image_2)



!python test.py

from google.colab.patches import cv2_imshow

from skimage import io
import cv2 as cv


image = io.imread('./hazy_test/My project-1.png')
image_2 = cv.cvtColor(image, cv.COLOR_BGR2RGB)
cv2_imshow(image_2)

image = io.imread('./facades/Ours_UIEB/My project-1.png')
image_2 = cv.cvtColor(image, cv.COLOR_BGR2RGB)
cv2_imshow(image_2)